### ISSUE TITLE
potter plugin list on fresh install fails

### ISSUE THREAD

**Issue by andrewdeandrade** [uber-archive/potter#2]
```
uber@aandrade:~/code$ potter plugin list

/usr/lib/node0.10/lib/node_modules/potter/cli/builtin/plugin.js:252
        if(err) throw err;
                      ^
Error: spawn ENOENT
    at errnoException (child_process.js:988:11)
    at Process.ChildProcess._handle.onexit (child_process.js:779:34)
```

Once you do `plugin install potter-playdoh-plugin` at least once, this gets fixed and you get 

```
uber@aandrade:~/code$ potter plugin list
 * (empty)
```

**Comment by Raynos** [comment]
Yes there was a known bug with something :( we should fix it
